### ISSUE TITLE
Plugin installation issue

### ISSUE THREAD

**Issue by Dog-brother0113** [zombieyang/sd-ppp#1]
This plugin is great because I know how to run it, but unfortunately, I don't know exactly how to operate the "run npm install and npm build in Photoshop directory." you wrote in the middle. After all, I am just an artist and not an IT engineer. Can you use text and graphics to describe in detail how to operate it? Thank you

**Comment by Dog-brother0113** [comment]
这个插件很棒，因为我在我朋友电脑上看到了怎么操作，很舒服，但是在我电脑上一直部署不了，一直没有用，大佬救救我

**Comment by Dog-brother0113** [comment]
我知道我的问题所在并且已经解决了，再次感谢作者开发出来的插件，真的非常好用

**Comment by liujvnes** [comment]
> 我知道我的问题所在并且已经解决了，再次感谢作者开发出来的插件，真的非常好用

请问你是怎么解决的？

**Comment by zombieyang** [comment]
I think it is because you didn't install Node.js

I can optimize it later.

**Comment by Dog-brother0113** [comment]
> > 我知道我的问题所在并且已经解决了，再次感谢作者开发出来的插件，真的非常好用
> 
> 请问你是怎么解决的？

需要先安装一个可以运行npm的程序（我不记得是啥了）
然后按照作者photoshop里面给的说明安装就可以了
安装起来比较复杂 但是安装好了之后就可以无痛连接了
