### ISSUE TITLE
Usage issues

### ISSUE THREAD

**Issue by Dog-brother0113** [zombieyang/sd-ppp#16]
Every time I use this tool, after opening PS, it cannot directly connect to ComfyUI. I still need to open the UXP development tool and run sd-ppp to connect PS and ComfyUI. Is this normal？

**Comment by zombieyang** [comment]
It's up to your installation way. If you put .cxx into the plugins directory of PS, I think UXP tool is not needed

**Comment by Dog-brother0113** [comment]
Thank you very much. I have already resolved this issue.
