### ISSUE TITLE
能不能支援直接放在 Adobe Photoshop XXXX\Plug-ins 的安裝模式

### ISSUE THREAD

**Issue by bluelovers** [zombieyang/sd-ppp#17]
試著將 `sd-ppp\photoshop\dist` 放到 `C:\Program Files\Adobe\Adobe Photoshop 2024\Plug-ins\sd-ppp`

但似乎沒有安裝成功

![image](https://github.com/zombieyang/sd-ppp/assets/167966/781ef7bd-8e0d-483f-9e77-f956a9f3fc2b)

**Comment by zombieyang** [comment]
修复了，感谢反馈
