### ISSUE TITLE
PS里似乎不能运行插件

### ISSUE THREAD

**Issue by tzhi4** [zombieyang/sd-ppp#24]
PS版本是25.5.1
这是找不到插件吗？
![屏幕截图 2024-08-03 215824](https://github.com/user-attachments/assets/070d229b-6346-48d5-9fc2-f898da82a5a6)
![屏幕截图 2024-08-03 215910](https://github.com/user-attachments/assets/34c4d116-331a-418a-b743-868f66fb291a)
![屏幕截图 2024-08-03 220025](https://github.com/user-attachments/assets/05a79b93-47db-4ab0-9382-dd1dfedda8c2)

**Comment by zombieyang** [comment]
我目前也不是太搞得清楚放Plug-in目录里的原理，有时候可以有时候不可以。不可以的时候从`Plug-in/Generator`移到`Plugin-in`或者反之就又可以了。
如果你一直不行，去QQ群再问一下别人的经验

**Comment by tzhi4** [comment]
> 我目前也不是太搞得清楚放Plug-in目录里的原理，有时候可以有时候不可以。不可以的时候从移到或者反之就又可以了。 如果你一直不行，去QQ群再问一下别人的经验`Plug-in/Generator``Plugin-in`
移动到Plugin-in就正常了
