### ISSUE TITLE
把ps 卡死了

### ISSUE THREAD

**Issue by huanli11** [zombieyang/sd-ppp#26]
<img width="1018" alt="截图：20240807102604" src="https://github.com/user-attachments/assets/4135990a-5ab1-4e60-8a84-8c2380af3ff2">
以前没问题  更新了几次comfyui 就不能用了

**Comment by zombieyang** [comment]
以前是啥时候？

**Comment by huanli11** [comment]
> 以前是啥时候？

2天前

**Comment by zombieyang** [comment]
你PS版本是多少？

**Comment by huanli11** [comment]
> 你PS版本是多少？

更新后好了
