### ISSUE TITLE
返回ps图层

### ISSUE THREAD

**Issue by huanli11** [zombieyang/sd-ppp#27]
现在的直接发到ps里 会出现图像不匹配 大小 p图要对齐有点麻烦  我现在都是搭配另个插件 他是发送到窗口处点击就导入到ps里智能对象了 就是不太稳定 有时候一直连不上ps  
<img width="708" alt="截图：20240809124506" src="https://github.com/user-attachments/assets/efe46187-dc92-474e-8885-053caf0da52d">

**Comment by zombieyang** [comment]
具体的发送设置/ps画布宽高/图片的宽高是怎样的

**Comment by huanli11** [comment]
The image import size seems to be different from the export size, sometimes it will be larger and sometimes it will be smaller. It is best to import the maximum size into ps, and the size should be appropriate in the way of smart objects

**Comment by huanli11** [comment]
图像导入尺寸，好像和在导出尺寸不太一样，有时候会大，有时候会小些。最好最大尺寸导入ps，以智能对象的方式应该尺寸就合适

**Comment by kerker93** [comment]
哈哈，一样一样，这个返图智能对象或者自动缩放填满原始图位置或选区 确实是目前最影响专业可用性的地方了

**Comment by huanli11** [comment]
工作流 里有缩放节点  放大了用那个插件可以直接放进ps里，  工作流要是没缩放节点还好

**Comment by zombieyang** [comment]
我今天试了一下，智能对象的API比较不稳定。对于这样的需求，通过这样的方式实现是否可以达成目的？

- 在传送图片之前，先创建好智能对象，放在对应位置
- 双击打开这个智能对象的psb，传送的时候将document设为该psb
- 发送

**Comment by kerker93** [comment]
> 我今天试了一下，智能对象的API比较不稳定。对于这样的需求，通过这样的方式实现是否可以达成目的？
> 
> * 在传送图片之前，先创建好智能对象，放在对应位置
> * 双击打开这个智能对象的psb，传送的时候将document设为该psb
> * 发送
那操作就十分繁琐，偶尔可以，但是专业工作就无法承受这个效率降低了。nima那个没有选区内图生图方式，遇到这种情况就是你说的方式去勉强实现的，就因为这个还一直在用auto囧，这个太关键了，要的就是“指哪打哪”的感觉。其实智能对象倒不是必须，图像大小差异可以自己工作流内前后大小一致化处理不难。如果智能对象置入有麻烦，能把选区模式返回的图的左上角坐标对齐原来选区的左上角么？这样只要图大小一致，就近似是置入选区效果了。这样新用户如果工作流改变了图大小，看到左上角能对齐 也会回过头优化自己工作流，而不是觉得插件有问题了

**Comment by kerker93** [comment]
> 我今天试了一下，智能对象的API比较不稳定。对于这样的需求，通过这样的方式实现是否可以达成目的？
> 
> * 在传送图片之前，先创建好智能对象，放在对应位置
> * 双击打开这个智能对象的psb，传送的时候将document设为该psb
> * 发送

那操作就十分繁琐，偶尔可以，但是专业工作就无法承受这个效率降低了。nima那个没有选区内图生图方式，遇到这种情况就是你说的方式去勉强实现的，就因为这个还一直在用auto囧，这个太关键了，要的就是“指哪打哪”的感觉。其实智能对象倒不是必须，图像大小差异可以自己工作流内前后大小一致化处理不难。如果智能对象置入有麻烦，能把选区模式返回的图的左上角坐标对齐原来选区的左上角么？这样只要图大小一致，就近似是置入选区效果了。这样新用户如果工作流改变了图大小，看到左上角能对齐 也会回过头优化自己工作流，而不是觉得插件有问题了

**Comment by zombieyang** [comment]
> > 我今天试了一下，智能对象的API比较不稳定。对于这样的需求，通过这样的方式实现是否可以达成目的？
> > 
> > * 在传送图片之前，先创建好智能对象，放在对应位置
> > * 双击打开这个智能对象的psb，传送的时候将document设为该psb
> > * 发送
> 
> 那操作就十分繁琐，偶尔可以，但是专业工作就无法承受这个效率降低了。nima那个没有选区内图生图方式，遇到这种情况就是你说的方式去勉强实现的，就因为这个还一直在用auto囧，这个太关键了，要的就是“指哪打哪”的感觉。其实智能对象倒不是必须，图像大小差异可以自己工作流内前后大小一致化处理不难。如果智能对象置入有麻烦，能把选区模式返回的图的左上角坐标对齐原来选区的左上角么？这样只要图大小一致，就近似是置入选区效果了。这样新用户如果工作流改变了图大小，看到左上角能对齐 也会回过头优化自己工作流，而不是觉得插件有问题了

这个可以，我先搞回图对齐选区吧

**Comment by zombieyang** [comment]
1.3.0已添加回图到选区能力
