### ISSUE TITLE
Feature request: Sending image to Photoshop when there is no open/active document

### ISSUE THREAD

**Issue by Jonseed** [zombieyang/sd-ppp#29]
I'd like to be able to send an image from Auto1111 to Photoshop when there is no open/active document in Photoshop. It would just open the image in Photoshop. Is that possible? Currently, if there is no open/active document in Photoshop, then clicking the send button does nothing. Perhaps an option could be added in the sdppp_send_document dropdown menu for "New Document."

**Comment by zombieyang** [comment]
that's make sense.
But I wonder....How can you open any plugin's UI when you are not opening any document?

**Comment by Jonseed** [comment]
Does the plugin's UI need to be open to send an image to Photoshop? Or does it just need to be "connected" on the backend?

**Comment by Jonseed** [comment]
The plugin seems to be working even without any document open in Photoshop.

![Screenshot 2024-08-14 220851](https://github.com/user-attachments/assets/bebc5a12-b2c2-4ce3-97dc-5646465d753f)

**Comment by zombieyang** [comment]
<img width="600" alt="image" src="https://github.com/user-attachments/assets/8eebcfd0-41a8-493f-ab94-269e0abd7bf2">
I don't know, my photoshop will show this UI when I don't open any document.

**Comment by Jonseed** [comment]
I get that screen when Photoshop is first started or when all documents are closed. But if I click the top Plugins menu, then SD-PPP, and then Connect SD or ComfyUI, it shows me the UI with no document open.

![Screenshot 2024-08-15 060550](https://github.com/user-attachments/assets/f5818978-faa1-42e6-93bc-99872a2f8748)

**Comment by zombieyang** [comment]
Oh, thanks.
fixed in main branch.
