### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by Dog-brother0113** [zombieyang/sd-ppp#3]
Can you create a button for refreshing nodes, so that you don't have to refresh the page every time
【是否可以做一个刷新节点的按钮之类的，这样不用每次都刷新页面了】

**Comment by zombieyang** [comment]
planning for it

**Comment by tianlang0704** [comment]
#4 Adding some ps history check to enable auto queue instant mode and change mode :D.

**Comment by zombieyang** [comment]
done in 0.0.2
