### ISSUE TITLE
will you make this support for sd webui forge?

### ISSUE THREAD

**Issue by jasoncow007** [zombieyang/sd-ppp#31]
flux now can work on forge, sd-ppp is an advantage

**Comment by zombieyang** [comment]
I think SDWebUI and SDWebUIForge is the same.
Isn't it work now?

**Comment by jasoncow007** [comment]
but it seems not

**Comment by zombieyang** [comment]
> but it seems not

well, I tested. Seems Forge changed a lot since my last test. I'll fix it soom

**Comment by zombieyang** [comment]
broke again after
[93b40f355e74a29b32e96d69455cc638fae06e83](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/93b40f355e74a29b32e96d69455cc638fae06e83)

**Comment by AnttiHuovilainen** [comment]
I'm using ReForge, which should remain compatible with A1111. Clicking the SD-PPP button just shows an empty darkened screen with a single X-button in the corner. Clicking "Generate" from Photoshop does the same as hitting Generate in ReForge's current screen.

Is this a known issue?

**Comment by zombieyang** [comment]
> I'm using ReForge, which should remain compatible with A1111. Clicking the SD-PPP button just shows an empty darkened screen with a single X-button in the corner. Clicking "Generate" from Photoshop does the same as hitting Generate in ReForge's current screen.
> 
> Is this a known issue?

Not yet, I've never heard about ReForge. I will check it later.

**Comment by AnttiHuovilainen** [comment]
ReForge is a fork of Forge that took the old codebase ~3-4 months ago (that uses Gradio 3) and added updates that shouldn't break plugins.

I also noticed that with the latest SD-PPP (updated yesterday) the Photoshop plugin download button in Settings screen has changed into one with "undefined" text that's grayed out. The button was still working in the version from a week or so ago.

**Comment by zombieyang** [comment]
> ReForge is a fork of Forge that took the old codebase ~3-4 months ago (that uses Gradio 3) and added updates that shouldn't break plugins.
> 
> I also noticed that with the latest SD-PPP (updated yesterday) the Photoshop plugin download button in Settings screen has changed into one with "undefined" text that's grayed out. The button was still working in the version from a week or so ago.

I try the reforge today but it seems like all works well.

**Comment by zombieyang** [comment]
finished in 1.4.0
