### ISSUE TITLE
从ps里加载图片和发送图片到PS出错

### ISSUE THREAD

**Issue by HEITAOKAKA** [zombieyang/sd-ppp#32]
![image](https://github.com/user-attachments/assets/4948d64a-5769-4add-b3f5-930d5eb078e2)
今天不知道什么原因，从PS中加载图层到comfyui和发送图片到PS都开始报错，ps中显示是连接着comfyui的，用的也是以前可以正常使用的工作流，下面是报错信息
got prompt
Failed to validate prompt for output 2:
* Get Image From Photoshop Layer 1:
  - Value not in list: use_layer_bounds: '### The Canvas ###' not in []
  - Value not in list: document: '### Active Document ###' not in []
  - Value not in list: layer_or_group: '组 1 (id:4)' not in []
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
请问这个该怎么解决呀？

**Comment by zombieyang** [comment]
回滚到8月12或以前的ComfyUI。它里面变了一些东西。
我会尽快兼容

**Comment by zombieyang** [comment]
先关了，原因同 #30 ，后续进度在 #30 周知
