### ISSUE TITLE
Function request【功能请求】多用户支持

### ISSUE THREAD

**Issue by Dog-brother0113** [zombieyang/sd-ppp#37]
We already have an AI server, so we used the comfyui of PS to connect to the server and found that only one person can connect at a time. Can we find some way to allow different people to connect at the same time.

【我们已经有了一个AI服务器，所以我们使用PS连接服务器的comfyui发现同一时间只能一个人连接，是否可以通过某种方式让同一时间不同的人同时连接。】

**Comment by zombieyang** [comment]
你们是用`--multi-user `参数启动comfy 的不

**Comment by Dog-brother0113** [comment]
啊 我们是用秋叶的启动器勾上了远程连接，然后大家都用的那台机子的IP地址使用comfyui

**Comment by zombieyang** [comment]
finished in 1.4.0
