### ISSUE TITLE
PUT A DAMN TUTORIAL!! I´m trying to use the workflow of light control but I don't even know if I'm in the right track.

### ISSUE THREAD

**Issue by ann7bel** [zombieyang/sd-ppp#41]
I select in the "get layer" node my own light gradient layer, but my result is a blank image in the preview. I suppose that's wrong because I can't get the desired results, but I don't also know if that's correct because I don't have a reference and only have a workflow that's giving me weird results, unlike the example in the thumbnail.

The exact same thing happens with the regional workflow. The thumbnails may have all the information we need, but once something goes wrong is impossible to know what to do. That's why a tutorial would be nice.

**Comment by zombieyang** [comment]
![image](https://github.com/user-attachments/assets/44789f7c-0e0e-4c4b-a890-c0fbcf54dcb2)

There are some tutorial in the end of github page... What step r u in? Did you able to connect your Photoshop yet?

**Comment by ann7bel** [comment]
I connected it fine. The problem is that I can't get the gradient layer correctly. I have the normal layer with the background removed and the gradient layer, so when I select each of those with "SDPPP Get Layer", the node that gets the normal layer works fine, but the node that should get the gradient layer only gets that white image.

I already tried with "selection only" on both, true and false. And on photoshop the only difference with the tutorial is that I don't have the layers in those folders, but I don't know if that's related.


![firefox_SEaj4FfAqD](https://github.com/user-attachments/assets/b59fbc5d-519a-4b3c-bd3d-c2a0f0007415)

**Comment by zombieyang** [comment]
In my workflow I selected the group which containing the gradient layer to get the gradient image data.

I remember that I have noticed this problem when I try to get from the gradient layer directly, then I switched to the group.



I will deep in later.

**Comment by ann7bel** [comment]
I see. Thanks.

It´s a great project. Of all the nodes that use photoshop this is the one that really let me get things done. I've been using the mask and everything else and it really works great.

**Comment by zombieyang** [comment]
https://www.youtube.com/watch?v=tQWqvpIuk_s
Tutorial for openart workflows. Only the lasso one but I think most of them are same.
