### ISSUE TITLE
Can't download ccx file

### ISSUE THREAD

**Issue by freshlesh3** [zombieyang/sd-ppp#42]
After successfully installing the SD-PPP custom node in ComfyUI/SwarmUI I can't download the .ccx file either from the menu (selecting it downloads a 404.htm file), and the option doesn't appear in the SDppp nodes for download.

**Comment by wuliang19869312** [comment]
me too,Same problem, can't find a place to download ccx

**Comment by zombieyang** [comment]
plugin can also be downloaded here: https://raw.githubusercontent.com/zombieyang/sd-ppp/refs/heads/main/javascript/plugins/sd-ppp_PS.ccx

could you provide a screenshoot or the url which reported 404?

**Comment by freshlesh3** [comment]
I am using Stability Matrix to run ComfyUI.  The URL the server uses is http://localhost:7801, and the console shows a websocket error:
ws: //localhost:7801/sd-ppp/?api_level=410&EIO=4&transport=websocket' failed:

**Comment by zombieyang** [comment]
> I am using Stability Matrix to run ComfyUI. The URL the server uses is http://localhost:7801, and the console shows a websocket error: ws: //localhost:7801/sd-ppp/?api_level=410&EIO=4&transport=websocket' failed:

Maybe Stability Matrix doesn't allow me to listen an extra websocket endpoint. I'll confirm it soon. I think official ComfyUI should work

**Comment by freshlesh3** [comment]
> > I am using Stability Matrix to run ComfyUI. The URL the server uses is http://localhost:7801, and the console shows a websocket error: ws: //localhost:7801/sd-ppp/?api_level=410&amp;EIO=4&amp;transport=websocket' failed:
> 
> Maybe Stability Matrix doesn't allow me to listen an extra websocket endpoint. I'll confirm it soon. I think official ComfyUI should work

Thanks for the effort

**Comment by zombieyang** [comment]
![image](https://github.com/user-attachments/assets/2bf24593-6ec4-4ba6-bb32-a326197a128e)
seems like I can connect with sdppp endpoint with my stability matrix comfyui

Maybe there are some other error?
