### ISSUE TITLE
I've installed it, but why does this link open a comfyui page and turn it into a browser?

### ISSUE THREAD

**Issue by wuliang19869312** [zombieyang/sd-ppp#43]
I've installed it, but why does this link open a comfyui page and turn it into a browser~ Do I need to set something else?

**Comment by wuliang19869312** [comment]
![Uploading 微信图片_20241022125059.png…]()

**Comment by wuliang19869312** [comment]
/
![微信图片_20241022125059](https://github.com/user-attachments/assets/9a6345bd-e47d-48d9-ba36-25bc26a81e75)

**Comment by zombieyang** [comment]
![image](https://github.com/user-attachments/assets/e078c433-29bc-433c-8523-407645ef953d)
click here to turn off the wide mode
