### ISSUE TITLE
Sending images to PS does not work

### ISSUE THREAD

**Issue by Lyqxyz** [zombieyang/sd-ppp#44]
![QQ浏览器截图20241023102000](https://github.com/user-attachments/assets/e61c75b4-2877-4a2f-b9db-c3ec99e4ad96)
![QQ浏览器截图20241023102035](https://github.com/user-attachments/assets/84d5ab46-d7f9-4581-acd3-91b4c851555d)

**Comment by zombieyang** [comment]
update and reinstall PS plugin plz.. I wrote a bug last night
