### ISSUE TITLE
Need a new tutorial for Photoshop Lasso Inpaint in ComfyUI.

### ISSUE THREAD

**Issue by ViratX** [zombieyang/sd-ppp#45]
Please if you can upload a new tutorial on how to use this feature. Currently I am just trying to randomly guess how to make it work, but getting stuck.

**Comment by zombieyang** [comment]
Chinese version here, published two days ago: https://www.bilibili.com/video/BV1npy5Y8E9j/
English version will take 2days more

**Comment by zombieyang** [comment]
https://www.youtube.com/watch?v=tQWqvpIuk_s
