### ISSUE TITLE
发送到ps的图片被压缩了

### ISSUE THREAD

**Issue by Lyqxyz** [zombieyang/sd-ppp#48]
ps画布的尺寸为512x512，发送到ps的尺寸为512x768，图片会被压缩。希望发送时可以创建智能对象
![QQ浏览器截图20241027090232](https://github.com/user-attachments/assets/ad74973e-4643-4da3-bbca-b82e04521a3a)
![QQ浏览器截图20241027090257](https://github.com/user-attachments/assets/2a248249-0a16-47f0-a5f3-0ee4b58b0d2c)

**Comment by zombieyang** [comment]
之前研究过智能对象，但没有一个转智能对象的接口是好用的。会导致后续步骤产生Bug。
比较建议的做法是你预先创建智能对象，双击打开成psb，然后Comfy发送的时候发送到该psb里。

另外下个版本会将默认发送行为改成“保持原尺寸或适配画布”而不是填满画布，可能会好一些。
