### ISSUE TITLE
Getting selection_only alpha only works if background is converted to layer

### ISSUE THREAD

**Issue by Jonseed** [zombieyang/sd-ppp#51]
I open an image in Photoshop, and it defaults to setting it as _background_ layer. But the `Get Image from Photoshop` alpha_out selection_only will only work if the background layer is converted to a regular layer. Can this be changed so that it also works with background layer?

**Comment by zombieyang** [comment]
It's a bug, I'll fix it soon

**Comment by zombieyang** [comment]
Done in 1.5.0
