### ISSUE TITLE
If hidden layer is active, it is made visible after getting image from Photoshop

### ISSUE THREAD

**Issue by Jonseed** [zombieyang/sd-ppp#53]
If I have a layer hidden in Photoshop, but it is the active layer (currently selected in layers panel), after getting image from Photoshop it is made visible. Can hidden layers stay hidden?

**Comment by zombieyang** [comment]
It is a strange bug from Photoshop and I did something to prevent it.
could you show me your layer layout? I tested the single layer getting situation and it is fine.

![image](https://github.com/user-attachments/assets/0983e8b5-e164-467b-824d-22d7a5deb387)

**Comment by Jonseed** [comment]
I can't reproduce it. I'll let you know if I see it again.

**Comment by Jonseed** [comment]
ok, I found it. Here is my layout, with the `boundary` layer hidden:

![Screenshot 2024-11-14 094451](https://github.com/user-attachments/assets/f68046e9-425b-4ef6-9ee1-7b9adae1d548)

And my workflow:

![Screenshot 2024-11-14 094608](https://github.com/user-attachments/assets/eb38c0e5-6398-4d31-898a-2215fba525b8)

After running the workflow, the `boundary` layer is unhidden, like this:

![Screenshot 2024-11-14 094634](https://github.com/user-attachments/assets/66d0dc56-b38b-481c-aa43-88fa33c1bbc0)

**Comment by Jonseed** [comment]
I think the layer is unhidden when an image is sent back from ComfyUI to Photoshop.

**Comment by zombieyang** [comment]
fixed in 1.5.1
