### ISSUE TITLE
I have sd-ppp installed inside forge, but I can't find the initialization icon

### ISSUE THREAD

**Issue by fly125** [zombieyang/sd-ppp#54]
![image](https://github.com/user-attachments/assets/99dcc19e-da1e-473e-b130-3fb0443a706b)
![image](https://github.com/user-attachments/assets/b2fb2173-a71e-4640-b7e2-77e749aa3894)

**Comment by zombieyang** [comment]
any error in the console?

**Comment by fly125** [comment]
> any error in the console?

There is nothing wrong with it
![image](https://github.com/user-attachments/assets/c5c8d4f4-b528-4551-bc87-96a03cc08af4)

**Comment by fly125** [comment]
> > any error in the console?
> 
> There is nothing wrong with it ![image](https://private-user-images.githubusercontent.com/90290679/384562371-c5c8d4f4-b528-4551-bc87-96a03cc08af4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMTY0MzYsIm5iZiI6MTczMTExNjEzNiwicGF0aCI6Ii85MDI5MDY3OS8zODQ1NjIzNzEtYzVjOGQ0ZjQtYjUyOC00NTUxLWJjODctOTZhMDNjYzA4YWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDAxMzUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzNjNGYyY2MzMzU1NmE2ZmZmNThlYmJhYWFiOGIzYmExZDE5MGZjN2E0MjU2YzQ4MGNmZGQ5ZGNjNmVkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gFjKi0adQtcrT6PGvBOgRxTBro4kkeg7RwP546UzOV4)

We are currently using the latest version of the webui_forge program and have not made any changes

**Comment by zombieyang** [comment]
Can you try again in 1.5.0?

**Comment by zombieyang** [comment]
I reproduced it and I think it is fixed in 1.5.3
