### ISSUE TITLE
多个不同设备的photoshop链接同一个服务器上的comfyui

### ISSUE THREAD

**Issue by bojimlee** [zombieyang/sd-ppp#56]
多个不同设备的photoshop链接同一个服务器上的comfyui时，sd-ppp节点似乎只会读取当前最新链接的photoshop的文档，其他之前链接的photoshop点击执行操作会报错提示找不到图层，如果设置的是当前文档则还是只会执行最新链接的Photoshop的文档。请问能否实现多个不同设备的photoshop链接同一个服务器上的comfyui时，仍能够准确识别并获取当前设备上执行操作的Photoshop的文档。

**Comment by zombieyang** [comment]
你的多个不同设备，显示出来的设备名是一样的吗？还是不一样的
就是文档名字中，斜杠前的那部份

**Comment by bojimlee** [comment]
![图层 8](https://github.com/user-attachments/assets/e388d504-6048-42b5-a687-7a05ac7f6b96)
这是在第一台电脑上的Photoshop执行成功
![图层 10](https://github.com/user-attachments/assets/914d21a8-0556-490d-981a-e1df3e1218a5)
这是在第二台电脑上的Photoshop上执行失败
![图层 12](https://github.com/user-attachments/assets/40f5a467-304c-4606-98de-547742e64d6a)
工作流里看斜杠前没有内容
![图层 13](https://github.com/user-attachments/assets/3b43edc9-1733-49db-914c-d85c161c66e7)

**Comment by zombieyang** [comment]
明白了，我想下怎么处理这种情况

**Comment by zombieyang** [comment]
fixed in 1.5.1

**Comment by bojimlee** [comment]
哇，确实可以识别了不同设备的Photoshop的文档了，但是我试了下还有个小问题，就是第一台设备可以通过插件界面去选择文档，但是其他设备在插件界面上选择文档无效会报错，只能进到编辑里面选择文档才有用。

**Comment by zombieyang** [comment]
1.5.2又修了下，你看看好了没

**Comment by bojimlee** [comment]
获取文档没问题了，但是图片发送回ps还是会发送到同一个photoshop上。

**Comment by zombieyang** [comment]
> 获取文档没问题了，但是图片发送回ps还是会发送到同一个photoshop上。

这个我没法复现出来了，发送是怎么配置的

**Comment by bojimlee** [comment]
![1](https://github.com/user-attachments/assets/5443a0cd-2b11-4da0-a5c9-2ea0f8d99505)
![2](https://github.com/user-attachments/assets/30a7ab29-fcb0-4c4d-8f36-3e09ef3fe307)
![3](https://github.com/user-attachments/assets/39da8ac4-8cf3-47ac-8bea-3415b5afe014)
你可以看到第二台电脑的ps执行插件的时候，发送图像到ps节点没有识别对应的当前文档，还是发到第一台电脑ps的猫文档那边

**Comment by zombieyang** [comment]
第二张小狗图的工作流里, 选择的PS确实是猫的那一个.
注意看一个是`PSpaq_lig`一个是`PSr0s_adm`

------
一个工作流可以只留一个GetDocument. 然后SendTo节点, 也从该GetDocument里拉一个GetLayerByID然后再连过来, 这样换GetDocument的值就都生效了.
