### ISSUE TITLE
Webview initialize failed

### ISSUE THREAD

**Issue by xueqing0622** [zombieyang/sd-ppp#58]
自定义了primitive节点，但是好像Photoshop里出不来
![image](https://github.com/user-attachments/assets/ab62d1f7-9662-4e30-98e7-9a58d4d639a7)
![image](https://github.com/user-attachments/assets/3bdb4520-b0f7-4776-a7e0-d6286f0f44d3)

**Comment by xueqing0622** [comment]
![Uploading image.png…]()
已经是最新版，win10系统

**Comment by xueqing0622** [comment]
没有特殊，http://127.0.0.1:8188/

**Comment by xueqing0622** [comment]
你在视频下面说不要安装这个插件， 我也没有装这个的。 https://[github](https://search.bilibili.com/all?from_source=webcommentline_search&keyword=github&seid=593589198879005156).com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/304

**Comment by xueqing0622** [comment]
更新版本后可以了，请问工作流要放在哪个路径才可以像你这样编辑。
![image](https://github.com/user-attachments/assets/061aeaf4-92f3-4ab3-b4bb-258528d44ed2)

我的现在没有任何工作流找到
![image](https://github.com/user-attachments/assets/e222bcb2-c06d-42fc-80b0-8aeaffc70eb8)
 我工作流放在这里，是不是只能默认user的目录才可以
F:\ComfyUI\ComfyUI\user\xueqing_38bf7d36-946a-4fc7-8f24-422a7eea1102

**Comment by zombieyang** [comment]
新版ComfyUI的界面不是有那个工作流管理能力嘛。
你用它的工作流管理能力，保存在它里面的工作流我都能读取出来。
b站视频的开头十几秒的时候有提一嘴。

**Comment by xueqing0622** [comment]
> 新版ComfyUI的界面不是有那个工作流管理能力嘛。 你用它的工作流管理能力，保存在它里面的工作流我都能读取出来。 b站视频的开头十几秒的时候有提一嘴。

我就是一只用新版的工作流frontend用了很久，里面有很多工作流了。
只是问一下你读取工作流的方式是什么，会不会因为用户的不同会读不到

**Comment by zombieyang** [comment]
用的这个接口：
/api/userdata?dir=workflows&recurse=true&split=false&full_info=true

**Comment by xueqing0622** [comment]
> 用的这个接口： /api/userdata?dir=workflows&recurse=true&split=false&full_info=true
> 
> 你如果是懂代码的话，我给你发个邀请可以看代码。不过等后面稳定点我也会合回公开仓库的。
 还是等你更新吧，我是个美术，没这本事，这个ps控制函数有用。

**Comment by zombieyang** [comment]
> 知道原因了，我把启动命令--multi-user去掉，用default就能读了 看来还是不支持多用户。

多谢，我后续修复下

**Comment by xueqing0622** [comment]
测试一下，编辑的时候，按运行是在photoshop内置的浏览器跑的，（而且会卡一下），是否能跟不是编辑的时候一样，在网页端跑。
![image](https://github.com/user-attachments/assets/93a7b57d-2a6a-45e6-9184-c3df81992fa2)
![image](https://github.com/user-attachments/assets/83a09fc9-ae6b-4686-b656-012f1cc57cce)
![image](https://github.com/user-attachments/assets/2523c8fb-ebe1-416f-9099-8e1c2d0dfa0c)

**Comment by xueqing0622** [comment]
这个控制数值和读取到workflow下json模式一打开，非常卡

**Comment by zombieyang** [comment]
> 这个控制数值和读取到workflow下json有效后，非常卡

读取到workflow下json是什么意思？

**Comment by zombieyang** [comment]
> 测试一下，编辑的时候，按运行是在photoshop内置的浏览器跑的，（而且会卡一下），是否能跟不是编辑的时候一样，在网页端跑。 ![image](https://private-user-images.githubusercontent.com/114840118/388796893-93a7b57d-2a6a-45e6-9184-c3df81992fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI1NzQsIm5iZiI6MTczMjQ2MjI3NCwicGF0aCI6Ii8xMTQ4NDAxMTgvMzg4Nzk2ODkzLTkzYTdiNTdkLTJhNmEtNDVlNi05MTg0LWMzZGY4MTk5MmZhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk1OWYzZTZmZmZiYzhkNzMxN2U2OTJiNWQzZmNiN2VkOWJlNjE4ZDBjNWJlNTgwYWUxZmYyYjI2YTg4MjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.29QfzDBd15cmilA3KWnlFuh47U2_aRBYKscMqa9Esfg) ![image](https://private-user-images.githubusercontent.com/114840118/388796980-83a09fc9-ae6b-4686-b656-012f1cc57cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI1NzQsIm5iZiI6MTczMjQ2MjI3NCwicGF0aCI6Ii8xMTQ4NDAxMTgvMzg4Nzk2OTgwLTgzYTA5ZmM5LWFlNmItNDY4Ni1iNjU2LTAxMmYxY2M1N2NjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzFkYWUzNmFkNTNhN2MzZTdmODBlZWIxM2Q1MjM4MTU2ODdkYzllZWNiOGYxNzliZjM5M2Y5MDVhMWI5NmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uznngEl38UYPjXSqVQWAB3XoVIx2Go7Npe4oDGTgpts) ![image](https://private-user-images.githubusercontent.com/114840118/388797147-2523c8fb-ebe1-416f-9099-8e1c2d0dfa0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI1NzQsIm5iZiI6MTczMjQ2MjI3NCwicGF0aCI6Ii8xMTQ4NDAxMTgvMzg4Nzk3MTQ3LTI1MjNjOGZiLWViZTEtNDE2Zi05MDk5LThlMWMyZDBkZmEwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjQyZDZkOGM0OTdiZmJjNjY1OTQ2NjM0NGRjYzY4YTk0ZDQwM2JkMWExM2M4N2NiNjUyNTJmOWI2ZGQwYTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4GbXx-CHNRkb48M3-ISB_vRXlu2ZT8r0FDQIlX4YgZg)



> 测试一下，编辑的时候，按运行是在photoshop内置的浏览器跑的，（而且会卡一下），是否能跟不是编辑的时候一样，在网页端跑。 ![image](https://private-user-images.githubusercontent.com/114840118/388796893-93a7b57d-2a6a-45e6-9184-c3df81992fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI1NzQsIm5iZiI6MTczMjQ2MjI3NCwicGF0aCI6Ii8xMTQ4NDAxMTgvMzg4Nzk2ODkzLTkzYTdiNTdkLTJhNmEtNDVlNi05MTg0LWMzZGY4MTk5MmZhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk1OWYzZTZmZmZiYzhkNzMxN2U2OTJiNWQzZmNiN2VkOWJlNjE4ZDBjNWJlNTgwYWUxZmYyYjI2YTg4MjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.29QfzDBd15cmilA3KWnlFuh47U2_aRBYKscMqa9Esfg) ![image](https://private-user-images.githubusercontent.com/114840118/388796980-83a09fc9-ae6b-4686-b656-012f1cc57cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI1NzQsIm5iZiI6MTczMjQ2MjI3NCwicGF0aCI6Ii8xMTQ4NDAxMTgvMzg4Nzk2OTgwLTgzYTA5ZmM5LWFlNmItNDY4Ni1iNjU2LTAxMmYxY2M1N2NjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzFkYWUzNmFkNTNhN2MzZTdmODBlZWIxM2Q1MjM4MTU2ODdkYzllZWNiOGYxNzliZjM5M2Y5MDVhMWI5NmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uznngEl38UYPjXSqVQWAB3XoVIx2Go7Npe4oDGTgpts) ![image](https://private-user-images.githubusercontent.com/114840118/388797147-2523c8fb-ebe1-416f-9099-8e1c2d0dfa0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NjI1NzQsIm5iZiI6MTczMjQ2MjI3NCwicGF0aCI6Ii8xMTQ4NDAxMTgvMzg4Nzk3MTQ3LTI1MjNjOGZiLWViZTEtNDE2Zi05MDk5LThlMWMyZDBkZmEwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQxNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjQyZDZkOGM0OTdiZmJjNjY1OTQ2NjM0NGRjYzY4YTk0ZDQwM2JkMWExM2M4N2NiNjUyNTJmOWI2ZGQwYTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4GbXx-CHNRkb48M3-ISB_vRXlu2ZT8r0FDQIlX4YgZg)

我自己也喜欢这样，不过还是得想下交互，怎么让用户选择用哪个。

**Comment by zombieyang** [comment]
1.6.0已支持选择

**Comment by xueqing0622** [comment]
1.6很棒，请问
![image](https://github.com/user-attachments/assets/5703cbae-e9e6-48d1-922b-d309cfdfee60)
为什么点这里， 只在queue列表出现图片，还是在ps内部跑
![image](https://github.com/user-attachments/assets/b9866c7f-94e2-4339-9b56-e4f638c28097)
怎么可以在这里实时调参数，执行又可以在我打开的网页端跑
![image](https://github.com/user-attachments/assets/e346cd6f-348b-40bc-a6ec-f88bfc5b5515)

**Comment by xueqing0622** [comment]
而且进入编辑模式，网页端出的图片 不会更新到_SDPPP_PSD_@这个文件

**Comment by zombieyang** [comment]
![image](https://github.com/user-attachments/assets/fe6b8752-ebdf-47e6-a05e-53b815293ec6)
点击这个网页ID可以用浏览器网页来当工作流运行媒介

**Comment by zombieyang** [comment]
> 而且进入编辑模式，网页端出的图片 不会更新到_SDPPP_PSD_@这个文件

这个漏了 我补下

**Comment by xueqing0622** [comment]
> ![image](https://private-user-images.githubusercontent.com/5595819/398622745-fe6b8752-ebdf-47e6-a05e-53b815293ec6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODIyMjAsIm5iZiI6MTczNTE4MTkyMCwicGF0aCI6Ii81NTk1ODE5LzM5ODYyMjc0NS1mZTZiODc1Mi1lYmRmLTQ3ZTYtYTA1ZS01M2I4MTUyOTNlYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDI1ODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAyODM2YjAwMmRmODMxODMxY2YyNjE3MTExNGIzYTcyNzFjN2E1MzU5ZjMxY2UwODQ4MmUyNmZiY2U2NWY4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GJ8H0lxQjQBffsjeSuO7qamx8vl7yqNXZJWYZG4H08k) 点击这个网页ID可以用浏览器网页来当工作流运行媒介

真的 能用了 太好了
哈哈，这个隐藏太好了，你要出一个视频说明一下，或者在这个字前面出一个文字标识，高亮时前面加web，灰度时前面加ps
![image](https://github.com/user-attachments/assets/db059c52-3273-4731-8ce4-e535d444a97e)

**Comment by xueqing0622** [comment]
进入编辑模式下，也会进入_SDPPP_PSD_@就完美了。

再问一下，如果我不想渲染完自己有_SDPPP_PSD_@这个文件，应该哪里关掉呢

**Comment by zombieyang** [comment]
我限定了只有PS触发的才会进 感觉用户应该都会有足够预期了
如果非要禁用，就在工作流里随便加一个mute掉的SendToPhotoshop节点
