### ISSUE TITLE
工作流是否可以按名称排序

### ISSUE THREAD

**Issue by huameiwei-vc** [zombieyang/sd-ppp#61]
工作流是否可以按名称排序吗
每次找的时候都比较混乱，添加一个新的工作流后，排序又找不到工作流了。
<img width="307" alt="image" src="https://github.com/user-attachments/assets/30091d46-be9b-4fed-a076-346e61b97e96">

**Comment by zombieyang** [comment]
这个排序目前应该是和Comfy里的一样，后面会加上读取看它里面哪些被点了书签，点了的就排前面

**Comment by huameiwei-vc** [comment]
> 这个排序目前应该是和Comfy里的一样，后面会加上读取看它里面哪些被点了书签，点了的就排前面

嗯嗯，还有个问题是，上一个版本还好，这个版本不知道为啥，ps 会特别卡，有时候甚至能卡死。。。

**Comment by zombieyang** [comment]
上一个是指1.4.x还是1.5.0？
如果1.4不卡那我看看是不是得提供一个干掉webview的选项。

**Comment by huameiwei-vc** [comment]
1.5.0，不知道因为什么会卡。
有时候会报错，报错原因好像是因为文档选择错误，不是选择了当前文档。

**Comment by zombieyang** [comment]
星标靠前能力1.5.3已提供.
卡顿问题1.5.2已修复
