### ISSUE TITLE
Feature Request: pause sending

### ISSUE THREAD

**Issue by Nekodificador** [zombieyang/sd-ppp#63]
First of all, thank you for building this node pack. This has literally transformed my entire workflow as a retoucher.

That being said, I’d love to tweak some adjustments inside Comfy without having to wait for Photoshop to resend the images, layers, and so on every time I press Queue. Would it be possible to temporarily pause the sending function? This would significantly reduce the waiting times and sould work similarly when you have a fixed seed and only the following part of the workflow is calculated.

Most of the time, once I send certain layers to Comfy, I don’t need them to be resent constantly (i.e, a controlnet layer). I just need to work with them and send various versions, inpaintings, or whatever else back to Photoshop.

**Comment by zombieyang** [comment]
Oh, get it. I think I should review the cache strategy in sd-ppp. Currently I don't cache any thing so it will re-get image every time even the layer is not changed.

**Comment by zombieyang** [comment]
Fixed in 1.5.2

**Comment by Nekodificador** [comment]
Thank you! This is a huge improvement. I noticed it only works with layers, but selections still load continuously. Would it be possible to add this functionality as well?

**Comment by zombieyang** [comment]
that's make sense, I will try next version

**Comment by zombieyang** [comment]
GetSelectionCache is provided in 1.5.3

**Comment by Nekodificador** [comment]
Hi again, for some reason this feature stopped working with the last update. I was doing some tutorials in Spanish and notice that the plugin is not caching images without modification, just keep loading again and again.

**Comment by zombieyang** [comment]
Seems like you got totally different result as #70 ..... Is it not working in all workflows?

**Comment by Nekodificador** [comment]
Yes, actually I built one from scratch and doesn't work like before

**Comment by zombieyang** [comment]
Could you provide the workflow for me to test? You can send a private message via discord.

I tested many of my workflows and they all work fine.

**Comment by Nekodificador** [comment]
Yeah no problem, I send you a DM

**Comment by zombieyang** [comment]
fixed (again) in 1.6.0
