### ISSUE TITLE
Boundaries probably broken

### ISSUE THREAD

**Issue by Nekodificador** [zombieyang/sd-ppp#65]
In last version, boundaries stop working. It happens with selections and layers. I've tried even with the official workflow for lasso inpaint (which worked fine in previous version) and I get this error mesage

define_comfyui_nodes_legacy.<locals>.SendImageToPhotoshopLayerNode.send_image() got an unexpected keyword argument 'bounds [optional]'

**Comment by zombieyang** [comment]
fixed. grateful for your feed back!
