### ISSUE TITLE
Boundary input in Get Selection node dissapeared

### ISSUE THREAD

**Issue by Nekodificador** [zombieyang/sd-ppp#66]
Boundary input in Get Selection node dissapeared since last update. Im not sure if this was intended, but previous versions allow to recreate the Inpaint Crop & Stich workflow and was very useful.

![image](https://github.com/user-attachments/assets/83814545-547a-4995-94b3-9d89ddf0c972)

If you can get this back, I suggest to add it a marging option that increase the bbox before croping. So it can function like others cropping nodes like LayerStyle or KJNodes

![image](https://github.com/user-attachments/assets/21993623-31ea-47bd-8881-a600e649d827)

**Comment by zombieyang** [comment]
Thanks for your feedback and I quickly fixed it!

And the second one, could I make a confirm that is it something like the builtin `GrowMask` from ComfyUI?

**Comment by Nekodificador** [comment]
Not exactly, I'll show you an example 
![image](https://github.com/user-attachments/assets/a94a0419-c6c3-45a2-bc0f-f69af605051b)

GrowMask is like a maximum filter, it just expand the alpha, and thats a problem if you need a sharp edge for inpainting. Also it is better to deal with that process in ComfyUI using core nodes.

The padding just make the boundary box larger whitout messing with mask edges. So it give **context** to the ksampler/controlnet to make a better inpainting and detailers.

**Comment by zombieyang** [comment]
Oh I see, I misunderstood the meaning of padding.
So it is actually a expand of the bounds and I think providing a `SDPPP expand boundary` node is OK, right?

**Comment by Nekodificador** [comment]
Yeah that would be perfect

**Comment by zombieyang** [comment]
boundary now become `MASK` type in 1.6.0 so you can expand it by `grow mask` node
