### ISSUE TITLE
能不能只读 一个文件夹或者打开的工作流

### ISSUE THREAD

**Issue by xueqing0622** [zombieyang/sd-ppp#68]
能不能只读 一个文件夹或者打开的工作流，我500个工作流左右，读了会卡死
![image](https://github.com/user-attachments/assets/e57f3114-c078-4abb-afbb-a2d3b7cf3a40)
![image](https://github.com/user-attachments/assets/98b97e0f-ccaa-47e2-9438-a17679b93d64)

**Comment by xueqing0622** [comment]
比如，可编辑只读workflow 下面的sd-ppp
![image](https://github.com/user-attachments/assets/d2df39d0-4133-46ce-9227-144330a89e04)
![image](https://github.com/user-attachments/assets/4764c9bb-2f13-476d-84cf-6eeb6d93a786)

**Comment by xueqing0622** [comment]
毕竟联动的就几个工作流，不可能所有工作流都去联动，
1 找一个文件夹查找方便
2 去掉很多等待时间，工作流一多真的卡

**Comment by zombieyang** [comment]
牛逼，500个也太专业了
我想一下怎么办

**Comment by xueqing0622** [comment]
感谢感谢，

**Comment by zombieyang** [comment]
文件夹视图1.6.1已加上
