### ISSUE TITLE
能否不用编辑工作流，默认输出几个项目

### ISSUE THREAD

**Issue by xueqing0622** [zombieyang/sd-ppp#69]
能否不用编辑工作流，默认输出几个项目，比如提示词，种子，重绘幅度百分比，图像大小。
一编辑工作流真的慢，还跟网页版的和桌面版的不是同一个，photoshop内置的浏览器也不好用
![image](https://github.com/user-attachments/assets/9bae8ef2-c42a-4a98-a8b8-e76b4ef08e42)

**Comment by zombieyang** [comment]
下个版本可以指定采用某个网页来跑。也会考虑直接把KSampler映射进Photoshop。就看你最后使用的是KSampler还是什么了

**Comment by xueqing0622** [comment]
不是ksampler啦，就是多几个输入的函数，让我们自己去连就好了。这样自由度好很多，甚至比comfyui-photoshop更好
比如：几个string，几个int，几个float，在photoshop能做到能输入就行，
comfyui-photoshop限死这几个也不好，有新的控制都不好加。

**Comment by xueqing0622** [comment]
这样就好了，comfyui搞个对接口， string1， string2，string3， int1，int2，int3，float1，float2，float3就好了 
![image](https://github.com/user-attachments/assets/219812fc-1667-4d09-be0e-dce6d1eb8071)

**Comment by zombieyang** [comment]
你这个情况, 我大概理解是你工作流太多了, 很多工作流在使用的时候要用同一批参数吧?

其中几个是现在就可以实现的
1. 宽高用`ParseLayerInfo`节点可以获取任意图层宽高或者是画布宽高
2. 提示词用`GetTextFromLayer`节点, 从文本图层里获取string. 只要你文本图层的命名有自己一套规范, 那就是可以通用的. 输入文本的时候直接改文本图层的内容就好了
3. float类型用`ParseLayerInfo`节点的透明度输出可以实现(不过只有0~1).
以上如果嫌节点过多可以打成一个groupNode.

你说的这个方式可以考虑 我晚点看看怎么弄.

**Comment by xueqing0622** [comment]
你说的方法我也去拜读了，也是一个好方式，
GetTextFromLayer这个从文本图层获取string我不是太习惯，photoshop太多层也麻烦，如果只是输入框就能搞定，就别去搞图层了。（建议而已）
感谢你的辛苦付出，跟ps联动真的很舒服！

**Comment by zombieyang** [comment]
1.6.0版本我支持了控件值的保存. 所以理论上你不同工作流的相同作用节点的名字相同的话 (比如都叫 `###Step`) 现在可以继承使用.

理论上可以缓解这个需求.

**Comment by xueqing0622** [comment]
可以用了，谢谢你的辛勤付出，好用！
