### ISSUE TITLE
从ps获取图像不会更新，获取选区可以更新

### ISSUE THREAD

**Issue by xueqing0622** [zombieyang/sd-ppp#70]
从ps获取图像不会更新，（就出现一次，画了新的元素和选中新的区域都不会更新），
获取选区可以更新。没有这样的问题
![image](https://github.com/user-attachments/assets/bbf810e7-7099-4630-870a-1c40e62d1d9a)

运行平台 comfyui-desktop

**Comment by xueqing0622** [comment]
网页版的也是一样，选区更新，获取图像只更新一次， 要修改或者reload node 才会更新

**Comment by zombieyang** [comment]
这个是在#63里刻意做的，如果没有修改图像内容的动作就不会重新获取。

你说的画了新的元素是用什么操作做的？

**Comment by xueqing0622** [comment]
就在画面画了新的东西也不会更新，

**Comment by zombieyang** [comment]
是画笔工具还是什么工具?
#63 是1.5.2

**Comment by zombieyang** [comment]
1.6.0修复了一些这个缓存相关的问题, 可以再试试

**Comment by xueqing0622** [comment]
可以了。 1.6太好用了， 感谢， 不过我的路径下文件太多，希望出一个之前提过，只读取指定某个文件夹下的工作流

**Comment by zombieyang** [comment]
> 可以了。 1.6太好用了， 感谢， 不过我的路径下文件太多，希望出一个之前提过，只读取指定某个文件夹下的工作流

马上
